# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.1
        
    - name: Test
      run: go test -v ./...

    - name: Build wallet win/x64
      run: env GOOS=windows GOARCH=amd64 go build -o msig_wallet_win_x64.exe cmd/wallet/main.go

    - name: Build wallet linux/x64
      run: env GOOS=linux GOARCH=amd64 go build -o msig_wallet_linux_x64 cmd/wallet/main.go

    - name: Build wallet darwin/x64
      run: env GOOS=darwin GOARCH=amd64 go build -o msig_wallet_darwin_x64 cmd/wallet/main.go

    - name: Build wallet darwin/arm64
      run: env GOOS=darwin GOARCH=arm64 go build -o msig_wallet_darwin_arm64 cmd/wallet/main.go

    - name: Build sign win/x64
      run: env GOOS=windows GOARCH=amd64 go build -o msig_sign_win_x64.exe cmd/sign/main.go

    - name: Build sign linux/x64
      run: env GOOS=linux GOARCH=amd64 go build -o msig_sign_linux_x64 cmd/sign/main.go

    - name: Build sign darwin/x64
      run: env GOOS=darwin GOARCH=amd64 go build -o msig_sign_darwin_x64 cmd/sign/main.go

    - name: Build sign darwin/arm64
      run: env GOOS=darwin GOARCH=arm64 go build -o msig_sign_darwin_arm64 cmd/sign/main.go

    - name: Prepare version file
      run: echo $GITHUB_SHA > version

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: dev
        artifacts: "msig_wallet_win_x64.exe,msig_wallet_linux_x64,msig_wallet_darwin_x64,msig_wallet_darwin_arm64,msig_sign_win_x64.exe,msig_sign_linux_x64,msig_sign_darwin_x64,msig_sign_darwin_arm64,version"
        prerelease: true