# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.1
        
    - name: Test
      run: go test -v ./...

    - name: Build wallet win/amd64
      run: env GOOS=windows GOARCH=amd64 go build -o ams_wallet_win_amd64.exe cmd/wallet/main.go

    - name: Build wallet linux/amd64
      run: env GOOS=linux GOARCH=amd64 go build -o ams_wallet_linux_amd64 cmd/wallet/main.go

    - name: Build wallet darwin/amd64
      run: env GOOS=darwin GOARCH=amd64 go build -o ams_wallet_darwin_amd64 cmd/wallet/main.go

    - name: Build wallet darwin/arm64
      run: env GOOS=darwin GOARCH=arm64 go build -o ams_wallet_darwin_arm64 cmd/wallet/main.go

    - name: Build sign win/amd64
      run: env GOOS=windows GOARCH=amd64 go build -o ams_sign_win_amd64.exe cmd/sign/main.go

    - name: Build sign linux/amd64
      run: env GOOS=linux GOARCH=amd64 go build -o ams_sign_linux_amd64 cmd/sign/main.go

    - name: Build sign darwin/amd64
      run: env GOOS=darwin GOARCH=amd64 go build -o ams_sign_darwin_amd64 cmd/sign/main.go

    - name: Build sign darwin/arm64
      run: env GOOS=darwin GOARCH=arm64 go build -o ams_sign_darwin_arm64 cmd/sign/main.go

    - name: Prepare version file
      run: echo $GITHUB_SHA > version

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: dev
        artifacts: "ams_wallet_win_amd64.exe,ams_wallet_linux_amd64,ams_wallet_darwin_amd64,ams_wallet_darwin_arm64,ams_sign_win_amd64.exe,ams_sign_linux_amd64,ams_sign_darwin_amd64,ams_sign_darwin_arm64,version"
        prerelease: true